import type { SaboteurId, SaboteurProfile } from "./types";

export const PROFILES: Record<SaboteurId, SaboteurProfile> = {
  kibr: {
    id: "kibr",
    name: "Kibr",
    arabic: "كِبْر",
    register: "Ego",
    definition: "Arrogance. The refusal to be wrong.",
    voice: "“The market is overreacting. It needs room. One more candle.”",
    counter: "Be wrong fast.",
    verdictLine: "You don't lose because you're wrong. You lose because you stay wrong.",
    profile: [
      "You don't move stops because you're careless. You move them because being wrong feels like dying a little, and you'd rather pay money than admit it. That's kibr. Arrogance, but quieter than the word sounds. It doesn't strut. It explains.",
      "In your head it sounds reasonable. The market is overreacting. This doesn't make sense. It needs room. Give it one more candle.",
      "The trades it takes: the stop moved twice, then deleted. The loser you added to, because a better average felt like a better argument. The trade you held because you'd already called it out loud, and exiting meant someone saw.",
      "The lie it tells you: that refusing to fold is strength. It isn't. It's just expensive.",
      "The counter-discipline is one motion: be wrong fast. Stop hit, flat, same breath. Your stop is not a question the market asks you. It's the answer you already gave.",
      "The next thirty days train that motion until it stops hurting. It will not stop hurting by day thirty. It will stop deciding.",
    ],
  },
  tama: {
    id: "tama",
    name: "Tamaʿ",
    arabic: "طَمَع",
    register: "Greed",
    definition: "Greed. The appetite that never says enough.",
    voice: "“You're seeing it well today. One more clean trade. Don't waste the rhythm.”",
    counter: "Enough is a number. Choose it before the open.",
    verdictLine: "Your problem was never finding trades. It's that you can't stop taking them.",
    profile: [
      "You hit your target at 10:40 and you're still in the chair at two. Not because there's a setup. Because stopping feels like leaving money in the street. That's tamaʿ. Greed, but from the inside it never feels like greed. It feels like ambition. It feels like work ethic.",
      "In your head it sounds responsible. One more clean trade and the day is excellent. You're seeing it well today. Don't waste the rhythm.",
      "The trades it takes: the fourth trade of a three-trade plan. The size you doubled because the last two won. The mediocre afternoon entry that gave back the morning.",
      "The lie it tells you: that the next trade is income. It isn't. The next trade is inventory you haven't paid for yet.",
      "The counter-discipline is a number: enough, chosen before the open, obeyed when it arrives. Anyone can write the number. You're going to learn to stop at it.",
      "Thirty days. First you'll count the appetite. Then you'll cage it. By the end, walking away early and green will feel like what it is: the entire job.",
    ],
  },
  ghadab: {
    id: "ghadab",
    name: "Ghadab",
    arabic: "غَضَب",
    register: "Anger",
    definition: "Anger. Trading as retaliation.",
    voice: "“It hunted your stop. You're not ending the day red. Get it back. Now.”",
    counter: "Fifteen minutes. Hands off. Every loss.",
    verdictLine: "You're not trading the market. You're fighting it. It hasn't noticed.",
    profile: [
      "The loss lands and something in you stands up. Ninety seconds later you're back in, bigger, in the same market that just took your money. You called it a re-entry. It was a retaliation. That's ghadab. Anger, holding your trading account.",
      "In your head it sounds like justice. It hunted my stop. I'm not ending the day like this. Get it back, now.",
      "The trades it takes: the instant re-entry, doubled. The third loss that became a fifth. The daily limit you blew through because red felt unbearable, so you made it redder.",
      "The lie it tells you: that refusing to walk away is fight. But the market is not an opponent. It's a price. It cannot hear you, and it has never once met you.",
      "The counter-discipline is fifteen minutes: any loss, hands off the platform, timed and logged. Not a punishment. A firebreak.",
      "Thirty days of building that wall. The fire doesn't go out by day thirty. It stops driving. It rides in the back, where it belongs.",
    ],
  },
  waswas: {
    id: "waswas",
    name: "Waswās",
    arabic: "وَسْوَاس",
    register: "Doubt",
    definition: "The whisper. Hesitation, second-guessing, the chase.",
    voice: "“Wait for confirmation. Check what the others think. Take the profit before it leaves.”",
    counter: "Decide once, at night, in peace. The session executes.",
    verdictLine: "You don't lack a plan. You lack a single hour of obeying one.",
    profile: [
      "You saw the setup at 9:50. The one you planned the night before. It triggered, you reached for the click, and a whisper said: what if. It hit target without you. At 11:15 you bought the top of the move out of regret. That's waswās. The whispering doubt. It never argues loudly. It just asks one more question.",
      "In your head it sounds careful. Wait for confirmation. Check what the others think. Take the profit now, before it leaves.",
      "The trades it takes: none, when it should. The chase, after. The winner cut at a third of target. The bias flipped on one red candle.",
      "The lie it tells you: that one more confirmation will make you certain. Certainty isn't coming. It was never coming. There is only the plan, and whether your hands obey it.",
      "The counter-discipline is a single promise: decisions get made once, at night, in peace. The session executes them. You are the hands, not the committee.",
      "Thirty days of keeping that promise, until your own voice outranks the whisper.",
    ],
  },
};

export const SABOTEUR_ORDER: SaboteurId[] = ["kibr", "tama", "ghadab", "waswas"];
